name = "hono-app"
main = "src/index.ts"
compatibility_date = "2024-12-16"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# The actual values come from .dev.vars or secrets

[[d1_databases]]
binding = "DB"
database_name = "hono-app-db"
database_id = "aea74e28-1a98-427b-a107-006036fbfd3e"

[[kv_namespaces]]
binding = "TODO_CACHE"
id = "bb0b43af3b664ade934b2d935af5763d"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[observability.logs]
enabled = true