name = "hono-app"
main = "src/index.ts"
compatibility_date = "2024-12-16"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# The actual values come from .dev.vars or secrets

[[d1_databases]]
binding = "DB"
database_name = "hono-app-db"
database_id = "${CF_D1_DATABASE_ID}"

[[kv_namespaces]]
binding = "TODO_CACHE"
id = "${CF_KV_NAMESPACE_ID}"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1